################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

###############
### Caching ###
###############
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

#####################
### Notifications ###
#####################
notifications:
  email: false

#################
### SonarQube ###
#################
addons:
  sonarcloud:
    organization: "felixklauke"
    token:
      secure: JibN8HBjtK4P83h5S7bFqiO7YvR4QeHo5G+vzXIDOYB8mQOoFxMJymROIPIVW4alkLk2iAOmBWWvsGxrxLhCyAgWXqt6+nwPg6EAVsZe/33TQuaUQpGxDeooCM82nEJOCwmHwt5aXf0PoB/2S56obKe4OSjKKzRuwyDS0DcH0E95tRv4QC3ULbp//Odd1AWkNCUiOAZSKTFSv2HGSbN/LqfDRZjDh9ZfF7sNgIyviCQRqtECMrIyLO4lRv9waxb0Bw18+Re5tKyk0ddTk4ln9WdQoTl1z+hPFZ0GKRL4UoDR/kyoTD71wP663xhcFp2Kj8ukJkfVdWD02LtOoLmw33Qw9Ftj7KplJaZxeHp5Q+qcvYXyVIXpm8GbMewP9Nyt3bTj98ZwnfkrxW12Dbt1SXLZdehoKqR1asgMWNp9aa+HvsgKy50gE9z31GFiRfmKMuVypUcPFQvcVMp/p9p4zdHHbxeUCVTcITYs7aTrpW91G9HSYUOGqXNJKQ+jlgUEWnfEwsS7pxacfWhL0lExQbFtp/mB3dJvQhzxyL5fZexB3EAfq6tnBVdGM4wKmUAfGHveyT3iArUYfVRhS2dm1jR/A7NPxDWwwlrsISkVERKOuIBfh8ahMYDkraQMwm6q8gHTbn1W+r+m/fcKcwS/+v/TWCu2xu3VULMLTsyyAro=

####################
### Build script ###
####################
script:
  - mvn checkstyle:check
  - mvn install org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=FelixKlauke_maven-project-template

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: true

env:
  global:
  - secure: rhZtK4COFdVq2V0YhDccHTUA5V5D9dopsDfR4skZanDT4kVb8us0Rdr3As6kCbTeo2KhP40eRqnXmBt8iLvFyBMIEcFum6nuycOkUuz7L75F+7Bcw+RHBZ/DgQiWM3Wejcxfmy2/WvMp14kRmDdKzNMr+FLZaj4UrFqdQlDhZye+FyfmCuQYux6+96KXeMhIE94OmbJvfhEfCgaZwqriPHNZsQ1jCBkNzb1TjENvf7Gq+pAusADXDCosyVHFllptbR5kv2IoKT+mCTJw/XeeSXVsMWx+mC7cX8qm2RY57CS18C7aeVohWCOAZUe/4U8zED6sC/JndfKpoBwahf894KEgbQZglTyM6qsM6F+BHAB3M+VbDo/oXtowWYHul9fhzwZC/D166GHpC5AS040BEHKSzxQyG7UaRAsRQN/ThUIqWbjdam3xfNN66R6hXVjzzy8aplHrM2A1uoarCc7oNJtbocf0xTPRqo6nD3M26ttv4hn7G9gLzh7ZVcuIvIQcoaVAKpdU6gIJKp0d4AIcHxU0+C5qfOsSj0D/I3lzKkVjt1572k8HtZ5J6F/XipdpRhZ3GYiKbEEuFScbUoF0S5t6giUwjtdHgysgGBUzK4gqHaPkCaejAxpCljZoryLVQQ5WNHBmHG6o759XB+5swpluzaxMYqwhO+IsVr1RonU=
  - secure: Y1gClTrGkMFaJddSt3Wbk6hmDqCH9+GImL71XWvEv1utTu3TY81zypUM8tw5xFWFC3dNR5aIfTtlv1iF5aphAeTlou9J81lZCkkBE8ltB9m7fbAMSVCW8GYAwQvh4VnJHCb47IQU8ZcPtiQ4mhuQvPcYCRf5ljdFGSVVs87h0REBr5DnBGhJ27aEy2MJ8IsbtQdN2Yb68EVMdY5FeASD8XDRWSrJ4U+I2ayrEms519y7lRcwFzpk4VMgIvliBWc1J/JmJajWjfDPKxp7wDZpMo+MPVjjVcHCoikuAGm5G86TRcqCaLSR6Mo8GOdgGwSAs1cRCmT47oMQrwXyOE3gfLoihklI/YGPS9TsdrhvVFlGpcdQ7TBzbwtsCPRQZSYLz6XO8a2KQ6+icNXhjH/7IypWS3ZaQz2hrS46NeL9GOF3NgBHh2Qd0unWU/etv8sKc9D13hJbz9rVlSZOdZBqC7i7ngDtIO1wjwonH/rVYOSbOKDIrqQ3e2euRI9ysUnOyA9e8IChIrh5qXKwhMB7rfAOPAFx+A0nSl+iuaolQ741DhuFm0uxogCHiWCM5mcd4LFS/sz4fq9IiONWp6lnxEFu3p/oyxlqSCNEBNT4lXeQQ40vNluksWGDXvbQYzDZffMXBWLTgUXG4TTxPw3FNOObTkt4pTS11Da3ripfUeE=
